spring.application.name=rising-star-public-school

spring.datasource.url=jdbc:mysql://localhost:3307/risingStarPublicSchool
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

